parameters:
#    rakuten_experience.example.class: Rakuten\ExperienceBundle\Example

services:
#    rakuten_experience.example:
#        class: %rakuten_experience.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    repository.abstract:
        abstract:                                                 true
        public:                                                   false
        factory_service:                                          doctrine.orm.entity_manager
        factory_method:                                           getRepository

    repository.task:
        class:                                                    Rakuten\ExperienceBundle\Entity\TaskRepository
        parent:                                                   repository.abstract
        public:                                                   true
        arguments:                                                [ Rakuten\ExperienceBundle\Entity\Task ]