Rakut_experience:
    resource: "@RakutExperienceBundle/Resources/config/routing.yml"
    prefix:   /

RakutExperienceRest:
    resource: "@RakutExperienceBundle/Resources/config/routing_rest.yml"
    type: rest